# -*- coding: utf-8 -*-
"""Cipher2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xo_BDiY2UXWWmP9-GKON2J1dS1WZMG7x
"""

import time
key=list(input("Enter the keyword:\n"))
cipher=list(input("\nEnter text:\n"))
config=int(input("\nEncrypting (1) or Decrypting? (-1):\n"))
length=len(key)
keylist=list()
cipherlist=list()
cycle=0
text=""
for i in key:
  ordinal=ord(i)
  keylist.append(ordinal)
for i in cipher:
  cycle = cycle + 1
  ordinal=ord(i)+keylist[cycle%length]*config
  if(ordinal>=127):
    ordinal=ordinal%127+32
    cipherlist.append(ordinal)
  elif(ordinal<=31):
    ordinal=ordinal+95
    cipherlist.append(ordinal)
  else:
    cipherlist.append(ordinal)
for i in cipherlist:
  text=text+chr(i)
print("\n"+text+"\nClosing in:\n")
time.sleep(5)
print("3")
time.sleep(1)
print("2")
time.sleep(1)
print("1")
time.sleep(1)