# -*- coding: utf-8 -*-
"""lab3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iqnNVmYlHJKhfVcbG6Rxq9ueI4a8bZn5
"""

# Get the shift for the cipher, and text to encrypt.
shift=int(input("Amount to shift by:\n"))
text=list(input("\nEnter text to encrypt:\n"))

# Setting up objects for later.
olist=list()
enc_text=""

# Grab each character in the text, shift it,
# wrap around if necessary, and append.
for i in text:
  ordinal=ord(i)+shift
  if(ordinal>=127):
    ordinal=ordinal%127+32
    olist.append(ordinal)
  elif(ordinal<=31):
    ordinal=ordinal+95
    olist.append(ordinal)
  else:
    olist.append(ordinal)

# Grab each entry in list of ordinals, convert to a character,
# then add that character to an object to be printed out.
for i in olist:
  enc_text=enc_text+chr(i)
print("\nYour encrypted text:\n"+enc_text+"\n")

# Setting up new objects for deciphering process.
enc_text=list(enc_text)
odlist=list()
dec_text=""

# Grab each character, shift, wrap if necessary, append.
for i in enc_text:
  ordinal=ord(i)-shift
  if(ordinal>=127):
    ordinal=ordinal%127+32
    odlist.append(ordinal)
  elif(ordinal<=31):
    ordinal=ordinal+95
    odlist.append(ordinal)
  else:
    odlist.append(ordinal)

# Grab each entry, convert to character, add to object, print.
for i in odlist:
  dec_text=dec_text+chr(i)
print("Your original text should appear here.\nIf it doesn't match, something is wrong.\n\n"+dec_text)